blank_issues_enabled: true
contact_links:
  - name: Thunderstore
    url: https://thunderstore.io/c/schedule-i/p/HazDS/
    about: Download my mods from Thunderstore
  - name: Nexus Mods
    url: https://www.nexusmods.com/profile/HazDS/mods
    about: Download my mods from Nexus Mods
